### ISSUE TITLE
I fixed the usage examples so they run with the new API

### ISSUE THREAD

**Issue by murphyk** [D-K-E/graphical-models#15]
The usage examples at https://d-k-e.github.io/graphical-models/html/d3/db0/md_graphical-models_docs_mdpages_usage.html
do not run with the current code. I fixed the issues and put the new version here:
https://github.com/probml/pyprobml/blob/master/notebooks/misc/pygmodels_doc.ipynb

I also added a visualization of the chain graph here:
https://gist.github.com/murphyk/e157531793f87f3d1eb9542234e6bc7d
However I suggest you rename the variables so they match the notation in the book...

**Comment by D-K-E** [comment]
Wow! The man himself. Thank you for your contribution, I'll add the fix right away. 
For the variables, you mean instead of naming them as A, B, C, ..., they should be named as Smoking, Tuberculosis, ..., right ?

**Comment by murphyk** [comment]
Yes, for the variable names in the chain graph example, I mean: be consistent with the Cowell book.
For example, they write p(C,D | B,E) = phi(C,D,B) phi(C,B,E) 1/Z(B,E)
but you write p(H,I|B,D) = phi(H,I,B) phi(H,B,D) phi(B,D)
where H=Cough, I=Dysponea, B=Bronchitis, D=Either.
This is confusing.

**Comment by D-K-E** [comment]
Okay I see what you mean, I'll fix it right away

**Comment by D-K-E** [comment]
The latest commit [0a6ec0c](https://github.com/D-K-E/graphical-models/commit/0a6ec0cb59f5dd9ea84509608aa56021119f42c5) in `master` branch now updates the usage examples section of the [docs](https://d-k-e.github.io/graphical-models/html/d9/d4c/md_graphical_models_docs_mdpages_usage.html), related [notebooks](https://github.com/D-K-E/graphical-models/tree/master/examples) and aligns the names of variables in LWF-Chain graph example to those of Cowell as shown in [here](https://gist.github.com/murphyk/e157531793f87f3d1eb9542234e6bc7d). 
Thank you again for bringing this up.

The library is still undergoing heavy refactoring, and I plan to break backwards compatibility on a lot of the existing api for the next release. I am particularly unsatisfied about how random variables are handled currently. 
If you have any recommendations both in terms of features or in terms of api design, usage or others, I'd love to hear it.

**Comment by murphyk** [comment]
This is now much clearer. I suggest updating https://github.com/D-K-E/graphical-models/tree/master#usage-examples so it points to the new example notebooks, rather than the old page. 

(BTW I updated the image at https://gist.github.com/murphyk/e157531793f87f3d1eb9542234e6bc7d, so the single letter variable names match the book, rather than your old code)
