### ISSUE TITLE
Ask users with issues/need support to file a GitHub issue?

### ISSUE THREAD

**Issue by eigenfoo** [D-K-E/graphical-models#2]
[cc openjournals/joss-reviews/issues/3115]

From the review checklist:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Right now the [README](https://github.com/D-K-E/graphical-models#guide-for-contributors) outlines how users might contribute to the software, but doesn't explicitly ask users who have issues or need support to file an issue on GitHub. It's probably a safe bet from a user's perspective, but best to make this explicit on the README and/or documentation!

**Comment by D-K-E** [comment]
@eigenfoo I added two templates for helping users to add documentation, and explicitly mention filing an issue at the end. How does that look ?

**Comment by eigenfoo** [comment]
Great, thanks for adding!
