### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by ankurankan** [D-K-E/graphical-models#5]
I see that there is some information for contributors in the readme. But it would be nice to add a github contribution guide as well at: https://github.com/D-K-E/graphical-models/community. 

Ref: https://github.com/openjournals/joss-reviews/issues/3115

**Comment by D-K-E** [comment]
All right on it

**Comment by D-K-E** [comment]
I added the `CONTRIBUTING.md` file as requested. How does it look ?

**Comment by ankurankan** [comment]
@D-K-E Looks great. Thanks.
